"""add favorite_treat to dogs

Revision ID: 8f9f96d4d7fc
Revises: ba20e5b0c91d
Create Date: 2025-04-01 12:55:26.188130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9f96d4d7fc'
down_revision = 'ba20e5b0c91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_treat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('favorite_treat')

    # ### end Alembic commands ###
